<?php
require_once __DIR__ . '/src/Customer.php';
require_once __DIR__ . '/src/Ticket.php';
require_once __DIR__ . '/src/BookingItem.php';
require_once __DIR__ . '/src/Booking.php';
// require_once __DIR__ . '/src/StripeClient.php';
// require_once __DIR__ . '/src/PayFastSdk.php';
require_once __DIR__ . '/src/EmailService.php';
require_once __DIR__ . '/src/SmsClient.php';
require_once __DIR__ . '/src/LoyaltyService.php';
require_once __DIR__ . '/src/AnalyticsClient.php';
require_once __DIR__ . '/src/BookingService.php';
require_once __DIR__ . '/src/Payement/PayFastSdk.php';
require_once __DIR__ . '/src/Payement/StripeClient.php';
require_once __DIR__ . '/src/Payement/PayementStrategy.php';
require_once __DIR__ . '/src/Payement/StripeStrategy.php';
require_once __DIR__ . '/src/Payement/PayFastAdapter.php';
require_once __DIR__ . '/src/Payement/PayementFactory.php';
require_once __DIR__ . '/src/PriceCalculatorInterface.php';
require_once __DIR__ . '/src/BasePriceCalculator.php';
require_once __DIR__ . '/src/VipDiscount.php';
require_once __DIR__ . '/src/ThreeDaysDiscount.php';
require_once __DIR__ . '/src/PositivePrice.php';
require_once __DIR__ . '/src/BookingConfirmedObserverInterface.php';
require_once __DIR__ . '/src/EmailObserver.php';
require_once __DIR__ . '/src/SmsObserver.php';
require_once __DIR__ . '/src/LoyaltyObserver.php';
require_once __DIR__ . '/src/AnalyticsObserver.php';
require_once __DIR__ . '/src/BookingService.php';
